# SCRAPING THE NEEDED DATA

In [1]:
import brotli
import pandas as pd
import requests
import torch

from sentence_transformers import SentenceTransformer, util

In [7]:
model = SentenceTransformer('./sentence-transformers_all-mpnet-base-v2')

In [ ]:
# Set the API key and base URL for the TMDb API
api_key = 'de0ce2956064588ee289cb8da1cc9a77'
base_url = 'https://api.themoviedb.org/3/trending/all/day'

# Initialize an empty DataFrame to store the movie data
movies_df = pd.DataFrame()

# Set the maximum number of pages to retrieve
max_pages = 1005  # 20 movies per page
max_pages = int(max_pages)

# Set the language parameter for the API request
language = 'en-US'

# Loop through the pages and retrieve the movie data
for page in range(1, max_pages+1):
    # Construct the API request URL
    url = f'{base_url}?api_key={api_key}&language={language}&page={page}'
    
    # Make the API request and retrieve the movie data
    try:
        response = requests.get(url)
        movies = response.json()['results']
        
        # Convert the movie data to a DataFrame and append it to the movies_df
        movies_df = pd.concat([movies_df, pd.DataFrame(movies)], ignore_index=True)
        
    except:
        # If there is an error with the API request or response, print an error message
        print(f'Error on page {page}')

:

![image](https://image.tmdb.org/t/p/w300/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg)

In [4]:
movies_df

,adult,backdrop_path,id,title,original_language,original_title,overview,poster_path,media_type,genre_ids,...,vote_average,vote_count,name,original_name,first_air_date,origin_country,gender,known_for_department,profile_path,known_for
0,False,/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg,661374,Glass Onion: A Knives Out Mystery,en,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[9648, 53, 35]",...,7.108,1117.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,False,/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg,76600,Avatar: The Way of Water,en,Avatar: The Way of Water,Set more than a decade after the events of the...,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[878, 12, 28]",...,8.034,1517.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,False,/hoVuI69nygLQBJ4FqgRKnukDeKt.jpg,106541,NaN,en,NaN,More than a thousand years before the world of...,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[10759, 10765]",...,5.927,82.0,The Witcher: Blood Origin,The Witcher: Blood Origin,2022-12-25,[US],NaN,NaN,NaN,NaN
3,False,/98bqsUBVjXpbUt1fRkjn7hJQXrq.jpg,157080,NaN,en,NaN,An MI6 deputy's bright future takes a sharp tu...,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[18, 10759]",...,7.053,19.0,Treason,Treason,2022-12-26,[GB],NaN,NaN,NaN,NaN
4,False,/xmtXSBONN4fsznx0zo4NhJwHDTa.jpg,668482,Roald Dahl's Matilda the Musical,en,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[10751, 35, 14]",...,7.400,72.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19974,False,/gYZ7bTrd6m2D9TY4JV07gsLO1tZ.jpg,57568,The Intruder,th,เขี้ยวอาฆาต,"In an old house, a man is bitten to death by a...",/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie,"[27, 53]",...,4.778,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19975,False,/eIbVGwmHuk3JY5QKi2ROnoHEOVe.jpg,134101,NaN,ar,NaN,,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv,[18],...,0.000,0.0,The Velvet Silk,الحرير المخملي,2021-09-19,[],NaN,NaN,NaN,NaN
19976,False,/4kPDPL9rVtC3g7DiHfZtCu1rT0O.jpg,27517,The Man Who Laughs,en,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,"[18, 27, 9648]",...,7.384,147.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19977,False,/5bEeQS3eHJC9FPs3GtWc5DMpBIy.jpg,28892,Étoile,it,Étoile,An American ballerina arrives in Hungary to en...,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie,"[14, 9648, 10749]",...,5.600,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19978,False,/qHJe3nWhDaRk4LguKuYtQk4aA8y.jpg,128878,Crayon Shin-chan: Explosion! The Hot Spring's ...,ja,クレヨンしんちゃん 爆発！温泉わくわく大決戦,There's only one way to stop a filthy evil sci...,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie,"[16, 28, 35]",...,6.700,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
movies = movies_df[['id', 'original_title', 'original_name', 'overview', 'genre_ids', 'vote_average', 'original_language', 'adult', 'poster_path', 'media_type']]

In [6]:
alt_movies = movies
movies

,id,original_title,original_name,overview,genre_ids,vote_average,original_language,adult,poster_path,media_type
0,661374,Glass Onion: A Knives Out Mystery,NaN,World-famous detective Benoit Blanc heads to G...,"[9648, 53, 35]",7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie
1,76600,Avatar: The Way of Water,NaN,Set more than a decade after the events of the...,"[878, 12, 28]",8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie
2,106541,NaN,The Witcher: Blood Origin,More than a thousand years before the world of...,"[10759, 10765]",5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv
3,157080,NaN,Treason,An MI6 deputy's bright future takes a sharp tu...,"[18, 10759]",7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv
4,668482,Roald Dahl's Matilda the Musical,NaN,An extraordinary young girl discovers her supe...,"[10751, 35, 14]",7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie
...,...,...,...,...,...,...,...,...,...,...
19974,57568,เขี้ยวอาฆาต,NaN,"In an old house, a man is bitten to death by a...","[27, 53]",4.778,th,False,/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie
19975,134101,NaN,الحرير المخملي,,[18],0.000,ar,False,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv
19976,27517,The Man Who Laughs,NaN,"Gwynplaine, son of Lord Clancharlie, has a per...","[18, 27, 9648]",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie
19977,28892,Étoile,NaN,An American ballerina arrives in Hungary to en...,"[14, 9648, 10749]",5.600,it,False,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie
19978,128878,クレヨンしんちゃん 爆発！温泉わくわく大決戦,NaN,There's only one way to stop a filthy evil sci...,"[16, 28, 35]",6.700,ja,False,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie

In [7]:
movies.genre_ids = movies.genre_ids.replace([], 'Unknown')

C:\Users\HP\AppData\Local\Temp\ipykernel_7924\3715743290.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.genre_ids = movies.genre_ids.replace([], 'Unknown')

In [8]:
movies

,id,original_title,original_name,overview,genre_ids,vote_average,original_language,adult,poster_path,media_type
0,661374,Glass Onion: A Knives Out Mystery,NaN,World-famous detective Benoit Blanc heads to G...,"[9648, 53, 35]",7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie
1,76600,Avatar: The Way of Water,NaN,Set more than a decade after the events of the...,"[878, 12, 28]",8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie
2,106541,NaN,The Witcher: Blood Origin,More than a thousand years before the world of...,"[10759, 10765]",5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv
3,157080,NaN,Treason,An MI6 deputy's bright future takes a sharp tu...,"[18, 10759]",7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv
4,668482,Roald Dahl's Matilda the Musical,NaN,An extraordinary young girl discovers her supe...,"[10751, 35, 14]",7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie
...,...,...,...,...,...,...,...,...,...,...
19974,57568,เขี้ยวอาฆาต,NaN,"In an old house, a man is bitten to death by a...","[27, 53]",4.778,th,False,/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie
19975,134101,NaN,الحرير المخملي,,[18],0.000,ar,False,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv
19976,27517,The Man Who Laughs,NaN,"Gwynplaine, son of Lord Clancharlie, has a per...","[18, 27, 9648]",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie
19977,28892,Étoile,NaN,An American ballerina arrives in Hungary to en...,"[14, 9648, 10749]",5.600,it,False,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie
19978,128878,クレヨンしんちゃん 爆発！温泉わくわく大決戦,NaN,There's only one way to stop a filthy evil sci...,"[16, 28, 35]",6.700,ja,False,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie

In [9]:
movies.loc[:, 'original_title'] = movies['original_title'].combine_first(movies['original_name'])
movies.drop('original_name', axis=1, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_7924\2976205895.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.loc[:, 'original_title'] = movies['original_title'].combine_first(movies['original_name'])
C:\Users\HP\AppData\Local\Temp\ipykernel_7924\2976205895.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.drop('original_name', axis=1, inplace=True)

In [10]:
response_tv = requests.get(f'https://api.themoviedb.org/3/genre/tv/list?api_key=de0ce2956064588ee289cb8da1cc9a77&language=en-US')
genre_tv = response_tv.json()['genres']
genre_dict_tv = {genre["id"]: genre["name"] for genre in genre_tv}
genre_dict_tv

{10759: 'Action & Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 10762: 'Kids',
 9648: 'Mystery',
 10763: 'News',
 10764: 'Reality',
 10765: 'Sci-Fi & Fantasy',
 10766: 'Soap',
 10767: 'Talk',
 10768: 'War & Politics',
 37: 'Western'}

In [11]:
response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=de0ce2956064588ee289cb8da1cc9a77&language=en-US')
genres = response.json()["genres"]
genre_dict = {genre["id"]: genre["name"] for genre in genres}
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [12]:
movies = movies.dropna()

In [13]:
movies = movies.reset_index()
movies.drop('level_0', inplace=True, axis=1)

KeyError: "['level_0'] not found in axis"

In [ ]:
movies.drop('index', axis=1, inplace=True)

In [14]:

movies

,index,id,original_title,overview,genre_ids,vote_average,original_language,adult,poster_path,media_type
0,0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,"[9648, 53, 35]",7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie
1,1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,"[878, 12, 28]",8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie
2,2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,"[10759, 10765]",5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv
3,3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,"[18, 10759]",7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv
4,4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,"[10751, 35, 14]",7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie
...,...,...,...,...,...,...,...,...,...,...
18944,19974,57568,เขี้ยวอาฆาต,"In an old house, a man is bitten to death by a...","[27, 53]",4.778,th,False,/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie
18945,19975,134101,الحرير المخملي,,[18],0.000,ar,False,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv
18946,19976,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...","[18, 27, 9648]",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie
18947,19977,28892,Étoile,An American ballerina arrives in Hungary to en...,"[14, 9648, 10749]",5.600,it,False,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie
18948,19978,128878,クレヨンしんちゃん 爆発！温泉わくわく大決戦,There's only one way to stop a filthy evil sci...,"[16, 28, 35]",6.700,ja,False,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie

In [16]:
movies['final_genre'] = ''
for j in range(10000):
    temp=[]
    for i in movies['genre_ids'][j]:
        try:
            temp.append(genre_dict[i])
        except KeyError:
            temp.append(genre_dict_tv[i])
            
    movies['final_genre'][j] = temp

C:\Users\HP\AppData\Local\Temp\ipykernel_7924\834604259.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['final_genre'][j] = temp

In [17]:
movies.drop('genre_ids', axis=1, inplace=True)

In [18]:
movies

,index,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,final_genre
0,0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[Mystery, Thriller, Comedy]"
1,1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[Science Fiction, Adventure, Action]"
2,2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[Action & Adventure, Sci-Fi & Fantasy]"
3,3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[Drama, Action & Adventure]"
4,4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[Family, Comedy, Fantasy]"
...,...,...,...,...,...,...,...,...,...,...
18944,19974,57568,เขี้ยวอาฆาต,"In an old house, a man is bitten to death by a...",4.778,th,False,/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie,
18945,19975,134101,الحرير المخملي,,0.000,ar,False,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv,
18946,19976,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,
18947,19977,28892,Étoile,An American ballerina arrives in Hungary to en...,5.600,it,False,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie,
18948,19978,128878,クレヨンしんちゃん 爆発！温泉わくわく大決戦,There's only one way to stop a filthy evil sci...,6.700,ja,False,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie,

In [19]:
movies['genre'] = movies['final_genre']
movies.drop('final_genre', axis=1, inplace=True)

In [20]:
movies

,index,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre
0,0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[Mystery, Thriller, Comedy]"
1,1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[Science Fiction, Adventure, Action]"
2,2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[Action & Adventure, Sci-Fi & Fantasy]"
3,3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[Drama, Action & Adventure]"
4,4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[Family, Comedy, Fantasy]"
...,...,...,...,...,...,...,...,...,...,...
18944,19974,57568,เขี้ยวอาฆาต,"In an old house, a man is bitten to death by a...",4.778,th,False,/96vFoTktDIUgAgR58dosnvTGI0L.jpg,movie,
18945,19975,134101,الحرير المخملي,,0.000,ar,False,/jdQtKRdbInFQTq8Lcs5vSbWXFR6.jpg,tv,
18946,19976,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,
18947,19977,28892,Étoile,An American ballerina arrives in Hungary to en...,5.600,it,False,/AgezMjwwGt9bgSagC64W6C4o4xs.jpg,movie,
18948,19978,128878,クレヨンしんちゃん 爆発！温泉わくわく大決戦,There's only one way to stop a filthy evil sci...,6.700,ja,False,/kYDZKDB0mkAglbl2phJfLFJmKqe.jpg,movie,

In [21]:
movies = movies.loc[movies['vote_average']>0.000]

In [22]:
movies = movies[movies['original_language']=='en']
movies

,index,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre
0,0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[Mystery, Thriller, Comedy]"
1,1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[Science Fiction, Adventure, Action]"
2,2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[Action & Adventure, Sci-Fi & Fantasy]"
3,3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[Drama, Action & Adventure]"
4,4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[Family, Comedy, Fantasy]"
...,...,...,...,...,...,...,...,...,...,...
18936,19966,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,
18938,19968,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,
18941,19971,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,
18943,19973,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,
18946,19976,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,

In [23]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10911 entries, 0 to 18946
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   index              10911 non-null  int64
 1   id                 10911 non-null  int64
 2   original_title     10911 non-null  object
 3   overview           10911 non-null  object
 4   vote_average       10911 non-null  float64
 5   original_language  10911 non-null  object
 6   adult              10911 non-null  bool
 7   poster_path        10911 non-null  object
 8   media_type         10911 non-null  object
 9   genre              10911 non-null  object
dtypes: bool(1), float64(1), int64(2), object(6)
memory usage: 863.1+ KB

In [24]:
movies = movies.reset_index()
movies.drop('index', inplace=True, axis=1)

In [26]:
movies
movies.drop('level_0', axis=1, inplace=True)

In [27]:
movies

,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre
0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[Mystery, Thriller, Comedy]"
1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[Science Fiction, Adventure, Action]"
2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[Action & Adventure, Sci-Fi & Fantasy]"
3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[Drama, Action & Adventure]"
4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[Family, Comedy, Fantasy]"
...,...,...,...,...,...,...,...,...,...
10906,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,
10907,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,
10908,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,
10909,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,
10910,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,

In [32]:
# movies.to_parquet('./data/normal_movies.parquet')

In [ ]:
#import pandas as pd
#df = pd.read_parquet('./data/movies/normal_movies.parquet')

In [ ]:
#anime = df[df['original_language']=='ja'].index
#df.drop(anime, inplace=True)

In [34]:
movies.drop(5795, inplace=True)

In [35]:
movies

,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre
0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"[Mystery, Thriller, Comedy]"
1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"[Science Fiction, Adventure, Action]"
2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"[Action & Adventure, Sci-Fi & Fantasy]"
3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"[Drama, Action & Adventure]"
4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"[Family, Comedy, Fantasy]"
...,...,...,...,...,...,...,...,...,...
10906,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,
10907,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,
10908,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,
10909,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,
10910,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,

In [36]:
def unwrap_list(x):
    return ', '.join(x)

movies['genre'] = movies['genre'].apply(unwrap_list)

In [37]:
movies = movies.drop_duplicates(keep='firsta')

In [38]:
movies

,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre
0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"Mystery, Thriller, Comedy"
1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"Science Fiction, Adventure, Action"
2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"Action & Adventure, Sci-Fi & Fantasy"
3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"Drama, Action & Adventure"
4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"Family, Comedy, Fantasy"
...,...,...,...,...,...,...,...,...,...
10906,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,
10907,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,
10908,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,
10909,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,
10910,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,

In [39]:
np.unique(movies['genre'])

array(['', 'Action', 'Action & Adventure', ..., 'Western, Mystery',
       'Western, Romance', 'Western, Thriller, Action'], dtype=object)

In [40]:
movies.genre = movies.genre.replace('', 'unknown')
np.unique(movies['genre'])

C:\Users\HP\AppData\Local\Temp\ipykernel_7924\761856677.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies.genre = movies.genre.replace('', 'unknown')

array(['Action', 'Action & Adventure', 'Action & Adventure, Animation',
       ..., 'Western, Romance', 'Western, Thriller, Action', 'unknown'],
      dtype=object)

In [49]:
movies['combined'] = movies['original_title'] + ' ' + movies['genre'] + ' ' + movies['overview']

C:\Users\HP\AppData\Local\Temp\ipykernel_7924\3942089502.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['combined'] = movies['original_title'] + ' ' + movies['genre'] + ' ' + movies['overview']
C:\Users\HP\AppData\Local\Temp\ipykernel_7924\3942089502.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['combined'] = movies['combined'].str.replace('unknown', '')

In [50]:
movies.to_parquet('./data/movies.parquet')

In [6]:
df = pd.read_parquet('./data/movies/movies.parquet')
df

,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre,combined,combined2
0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"Mystery, Thriller, Comedy","Glass Onion: A Knives Out Mystery Mystery, Thr...","Mystery, Thriller, ComedyWorld-famous detectiv..."
1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"Science Fiction, Adventure, Action","Avatar: The Way of Water Science Fiction, Adve...","Science Fiction, Adventure, ActionSet more tha..."
2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"Action & Adventure, Sci-Fi & Fantasy","The Witcher: Blood Origin Action & Adventure, ...","Action & Adventure, Sci-Fi & FantasyMore than ..."
3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"Drama, Action & Adventure","Treason Drama, Action & Adventure An MI6 deput...","Drama, Action & AdventureAn MI6 deputy's brigh..."
4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"Family, Comedy, Fantasy","Roald Dahl's Matilda the Musical Family, Comed...","Family, Comedy, FantasyAn extraordinary young ..."
...,...,...,...,...,...,...,...,...,...,...,...
10185,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,unknown,Shameless Hall of Shame,
10186,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,unknown,A La Carte A first-generation college student...,A first-generation college student who gradua...
10187,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,unknown,Wrong Dolph Springer wakes up one morning to ...,Dolph Springer wakes up one morning to realiz...
10188,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,unknown,The Last Dragonslayer In a fantasy world wher...,In a fantasy world where magic is being super...
10189,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,unknown,"The Man Who Laughs Gwynplaine, son of Lord Cl...","Gwynplaine, son of Lord Clancharlie, has a pe..."

In [8]:
combined_embeddings = model.encode(df['combined'].tolist(), convert_to_tensor=True)

In [9]:
combined_embeddings

tensor([[ 0.0536,  0.0381, -0.0008,  ..., -0.0164, -0.0238, -0.0220],
        [-0.0071,  0.0600, -0.0321,  ...,  0.0431, -0.0156, -0.0187],
        [-0.0025, -0.0287,  0.0150,  ...,  0.0017,  0.0149,  0.0033],
        ...,
        [-0.0017,  0.0485,  0.0058,  ..., -0.0115,  0.0777,  0.0020],
        [ 0.0248, -0.0094,  0.0032,  ...,  0.0081, -0.0012, -0.0232],
        [ 0.0606,  0.0370,  0.0089,  ...,  0.0361,  0.0765, -0.0089]])

In [15]:
torch.save(combined_embeddings, './data/movies/combined_embeddings.pt')

In [16]:
combined2_embeddings = model.encode(df['combined2'].tolist(), convert_to_tensor=True)
torch.save(combined2_embeddings, './data/movies/combined2_embeddings.pt')

In [10]:
kk = [['1', '3', '4'],
      ['0', '4', '7']]

In [13]:
jj = []
for i in kk:
    jj.append(int(i))

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'list'

In [5]:
df['combined2'] = df['genre'] + df['overview']
df['combined2'] = df['combined2'].str.replace('unknown', ' ')

In [4]:
df.to_parquet('./data/movies/movies.parquet', compression='brotli')

In [32]:
df=df.reset_index()

In [34]:
df.drop('index', inplace=True, axis=1)

In [4]:
movies_index = df['id'].tolist()

dict_bytes = str.encode(str(movies_index))
compressed = brotli.compress(dict_bytes)

with open('./data/movies/id.brotli', 'wb') as f:
    f.write(compressed)

In [2]:
df = pd.read_parquet('./data/movies/movies.parquet')

In [3]:
df

,id,original_title,overview,vote_average,original_language,adult,poster_path,media_type,genre,combined,combined2
0,661374,Glass Onion: A Knives Out Mystery,World-famous detective Benoit Blanc heads to G...,7.108,en,False,/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg,movie,"Mystery, Thriller, Comedy","Glass Onion: A Knives Out Mystery Mystery, Thr...","Mystery, Thriller, ComedyWorld-famous detectiv..."
1,76600,Avatar: The Way of Water,Set more than a decade after the events of the...,8.034,en,False,/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg,movie,"Science Fiction, Adventure, Action","Avatar: The Way of Water Science Fiction, Adve...","Science Fiction, Adventure, ActionSet more tha..."
2,106541,The Witcher: Blood Origin,More than a thousand years before the world of...,5.927,en,False,/vpfJK9F0UJNcAIIeC42oJyKMnZQ.jpg,tv,"Action & Adventure, Sci-Fi & Fantasy","The Witcher: Blood Origin Action & Adventure, ...","Action & Adventure, Sci-Fi & FantasyMore than ..."
3,157080,Treason,An MI6 deputy's bright future takes a sharp tu...,7.053,en,False,/qOitarv5B5ydsScN3dkJPipYPg3.jpg,tv,"Drama, Action & Adventure","Treason Drama, Action & Adventure An MI6 deput...","Drama, Action & AdventureAn MI6 deputy's brigh..."
4,668482,Roald Dahl's Matilda the Musical,An extraordinary young girl discovers her supe...,7.400,en,False,/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg,movie,"Family, Comedy, Fantasy","Roald Dahl's Matilda the Musical Family, Comed...","Family, Comedy, FantasyAn extraordinary young ..."
...,...,...,...,...,...,...,...,...,...,...,...
10185,208736,Shameless Hall of Shame,,10.000,en,False,/ezSi7VR7247XbkwapsjCkF70ooB.jpg,tv,unknown,Shameless Hall of Shame,
10186,203968,A La Carte,A first-generation college student who graduat...,10.000,en,False,/760c8p3g9kebWC8OABs4Qhgvvg1.jpg,tv,unknown,A La Carte A first-generation college student...,A first-generation college student who gradua...
10187,83186,Wrong,Dolph Springer wakes up one morning to realize...,6.304,en,False,/qQtoH9yO5J3bBapLSvop0HWWfCq.jpg,movie,unknown,Wrong Dolph Springer wakes up one morning to ...,Dolph Springer wakes up one morning to realiz...
10188,431742,The Last Dragonslayer,In a fantasy world where magic is being superc...,5.900,en,False,/1aqqYXoLTER1N2mR9MD5CNGqxhA.jpg,movie,unknown,The Last Dragonslayer In a fantasy world wher...,In a fantasy world where magic is being super...
10189,27517,The Man Who Laughs,"Gwynplaine, son of Lord Clancharlie, has a per...",7.384,en,False,/iQXBMr4NzQst4X0rDU6MII6ZUOM.jpg,movie,unknown,"The Man Who Laughs Gwynplaine, son of Lord Cl...","Gwynplaine, son of Lord Clancharlie, has a pe..."